// GENERATED by @edgedb/generate v0.5.6

import type {Executor} from "edgedb";


export type RandomReturns = Array<{
  "maybe": Array<{
    "index": number | null;
    "content": string;
    "type": ("SINGLE" | "MULTI") | null;
  }>;
}>;

export function random(client: Executor): Promise<RandomReturns> {
  return client.query(`\
select Training {
   maybe: {
    index := [is TrainingPage].index ?? [is Question].index,
    content,
    [is Question].type,
   },
}`);

}
